"""Source code and detection constants for flext-infra project.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from flext_infra import t


class FlextInfraConstantsSourceCode:
    """Source code patterns, exclusion sets, and detection constants."""

    MERGE_CONFLICT_CONTROLS: ClassVar[t.VariadicTuple[t.Pair[str, str]]] = (
        ("current", "<<<<<<< "),
        ("ancestor", "||||||| "),
        ("separator", "======="),
        ("incoming", ">>>>>>> "),
    )
    "Git merge-control kinds and their immutable protocol tokens."
    TOML_SECTION_HEADER_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*\[([^\[\]]+)\]\s*(?:#.*)?$"
    )
    "Regex: one complete TOML table header with an optional comment."

    # --- Directory exclusion sets (was: class Excluded) ---
    COMMON_EXCLUDED_DIRS: ClassVar[frozenset[str]] = frozenset({
        ".git",
        ".agents-sync-home",
        ".test-tmp",
        ".venv",
        ".worktrees",
        "node_modules",
        "__pycache__",
        "dist",
        "dist-packages",
        "build",
        ".reports",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "site-packages",
        "venv",
    })
    "Common directories to exclude from analysis across all scripts."
    PYTHON_DISCOVERY_SKIP_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "vendor"
    }
    "Non-productive roots excluded while discovering Python analyzer surfaces."
    DOC_EXCLUDED_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "crg-reports",
        "incoming",
        "legado",
        "site",
    }
    "Live docs exclude generated sites and immutable or historical evidence roots."
    PYPROJECT_SKIP_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".claude.disabled",
        "context_test",
        "rope_ws",
        "tmp_flow_test",
        "tests",
        "examples",
        "legado",
    }
    "Directories to skip when scanning pyproject.toml files."
    CHECK_EXCLUDED_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".archive",
        ".claude",
        ".codex",
        ".cursor",
        ".gemini",
        ".opencode",
        ".beads",
        "reports",
        ".agents",
        # Runtime tool state (Serena memories, Kilo plans): regenerated caches,
        # never governed source — excluded from every quality-check surface.
        ".serena",
        ".kilo",
        ".omo",
        ".tmp",
        ".snapshots",
        ".benchmarks",
        ".hypothesis",
        ".vscode",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".pyrefly_cache",
        "htmlcov",
        "legado",
        "site",
        "target",
    }
    "Directories to exclude during quality checks."
    GITHUB_AGENT_PROJECTION_DIRS: ClassVar[frozenset[str]] = frozenset({
        "agents",
        "hooks",
        "instructions",
        "skills",
    })
    "GitHub provider directories owned by the agentsctl projection."
    ITERATION_EXCLUDED_PARTS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "dist-packages",
        "site-packages",
        "vendor",
        "venv",
    }
    "Path parts to skip during file iteration (superset of COMMON_EXCLUDED_DIRS)."
    VALIDATION_CLONE_EXCLUDES: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".archive",
        ".ropeproject",
        "htmlcov",
    }
    "Directories excluded when cloning a project tree for post-apply validation."
    WORKTREE_TRANSACTION_EXCLUDED_DIRS: ClassVar[frozenset[str]] = (
        COMMON_EXCLUDED_DIRS | {".pyrefly_cache", ".cache"}
    )
    "Cache directories excluded from isolated worktree transaction deltas."

    # --- Encoding (was: class Encoding) ---
    ENCODING_DEFAULT: ClassVar[str] = "utf-8"
    "Default text encoding for file operations."

    # --- Source code template constants and parsing patterns (was: class SourceCode) ---
    TOC_START: ClassVar[str] = "<!-- TOC START -->"
    "Marker for table of contents start."
    TOC_END: ClassVar[str] = "<!-- TOC END -->"
    "Marker for table of contents end."
    GENERATED_HEADER: ClassVar[str] = "<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->"
    "Header for markdown auto-generated content."
    GENERATED_SHELL_HEADER: ClassVar[str] = "# Generated by {source} - DO NOT EDIT\n"
    "Header for shell auto-generated content."
    FUTURE_ANNOTATIONS: ClassVar[str] = "from __future__ import annotations"
    "Standard future annotations import line."
    RUNTIME_MODEL_BASES: ClassVar[frozenset[str]] = frozenset({
        "BaseModel",
        "BaseSettings",
        "FlextModelsBase",
    })
    "Pydantic bases that resolve class-body annotations at runtime, not only for a type checker."
    ENCODING_COOKIE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^[ \t\f]*#.*?coding[:=][ \t]*[-\w.]+"
    )
    "Regex: Python source encoding cookie on a header line."
    CLASS_WITH_BASES_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^class\s+(\w+)\s*\(([^)]*)\)\s*:", re.MULTILINE
    )
    "Regex: ``class <name>(<bases>):`` — requires parentheses, captures bases."
    FROM_IMPORT_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s+(.+?)(?:\s*#.*)?$", re.MULTILINE
    )
    "Regex: from-import with optional trailing comment."
    FROM_IMPORT_BLOCK_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s*\((.*?)\)", re.MULTILINE | re.DOTALL
    )
    "Regex: multiline from-import block."
    REQUIRES_PYTHON_RE: ClassVar[t.RegexPattern] = re.compile(
        r'requires-python\s*=\s*"[>!=]*(\d+)\.(\d+)'
    )
    'Regex: ``requires-python = ">=3.X"`` — captures major and minor.'
    DEPENDENCY_VERSION_OP_RE: ClassVar[t.RegexPattern] = re.compile(r"[<>=!~]")
    "Regex: dependency version operator characters (used to split a name+spec)."

    REGEX_ERROR: ClassVar[type[Exception]] = re.error
    "Centralized alias for ``re.error`` so consumers needn't import ``re``."

    TOC_BLOCK_RE: ClassVar[t.RegexPattern] = re.compile(
        r"<!-- TOC START -->.*?<!-- TOC END -->", re.DOTALL
    )
    "Regex: TOC marker block (start..end), DOTALL."
    DUNDER_ALL_SINGLE_LINE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]\n]*)\]",
        re.MULTILINE,
    )
    "Regex: single-line ``__all__ = [...]`` declaration."
    DUNDER_ALL_MULTI_LINE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]]*?)\]",
        re.MULTILINE | re.DOTALL,
    )
    "Regex: multi-line ``__all__ = [...]`` declaration (DOTALL body)."
    BLANK_LINE_RUN_RE: ClassVar[t.RegexPattern] = re.compile(r"\n{4,}")
    "Regex: 4+ consecutive newlines — collapsed to triple newline."
    LEGACY_TYPEALIAS_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(\w+)\s*:\s*TypeAlias\s*=\s*(.+)$", re.MULTILINE
    )
    "Regex: legacy ``X: TypeAlias = expr`` (rewritten to PEP 695 ``type X = ...``)."

    @staticmethod
    def compile_multiline(pattern: str) -> t.RegexPattern:
        """Compile a user-supplied pattern with ``re.MULTILINE`` (centralized)."""
        return re.compile(pattern, re.MULTILINE)





    @staticmethod
    def compile(pattern: str, *, multiline: bool = False) -> t.RegexPattern:
        """Compile an arbitrary pattern (centralized so consumers needn't import re)."""
        return re.compile(pattern, re.MULTILINE if multiline else 0)

    @staticmethod
    def compile_class_base_with_generic(name: str) -> t.RegexPattern:
        r"""Compile ``<escaped name>(?:\[.*\])?`` for class-base + generic match."""
        return re.compile(rf"{re.escape(name)}(?:\[.*\])?")







    @staticmethod
    def escape(literal: str) -> str:
        """Escape ``literal`` for inclusion in a regex (centralized re.escape)."""
        return re.escape(literal)

    @staticmethod
    def compile_from_module_paren_open(module_name: str) -> t.RegexPattern:
        """Compile ``^from <module_name> import (`` for parenthesized-import detection."""
        return re.compile(rf"^from\s+{re.escape(module_name)}\s+import\s+\(")

    @staticmethod
    def compile_from_module_import_line(module_name: str) -> t.RegexPattern:
        """Compile ``^from <module_name> import .+$`` (MULTILINE) for whole-line replace."""
        return re.compile(
            rf"^from\s+{re.escape(module_name)}\s+import\s+.+$", re.MULTILINE
        )

    @staticmethod
    def compile_class_header_match(class_name: str) -> t.RegexPattern:
        r"""Compile ``^class <class_name>\b`` for header equality check."""
        return re.compile(rf"^class\s+{re.escape(class_name)}\b")

    @staticmethod
    def compile_class_header_search(class_name: str) -> t.RegexPattern:
        r"""Compile ``^class <class_name>\b`` (MULTILINE) for full-source search."""
        return re.compile(rf"^class\s+{re.escape(class_name)}\b", re.MULTILINE)











    @staticmethod
    def compile_function_def_block(name: str) -> t.RegexPattern:
        """Compile a regex matching the full def block of ``name`` (with decorators)."""
        return re.compile(
            rf"^((?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"def\s+{re.escape(name)}\s*\([^)]*\)[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*)",
            re.MULTILINE,
        )

    @staticmethod
    def compile_class_def_block(name: str) -> t.RegexPattern:
        """Compile a regex matching the full class block of ``name`` (with decorators)."""
        return re.compile(
            rf"^((?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"class\s+{re.escape(name)}\b[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*)",
            re.MULTILINE,
        )

    @staticmethod
    def compile_function_def_remove(name: str) -> t.RegexPattern:
        """Compile a regex matching the def block of ``name`` for removal (no outer capture)."""
        return re.compile(
            rf"^(?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"def\s+{re.escape(name)}\s*\([^)]*\)[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*",
            re.MULTILINE,
        )

    @staticmethod
    def compile_class_def_remove(name: str) -> t.RegexPattern:
        """Compile a regex matching the class block of ``name`` for removal (no outer capture)."""
        return re.compile(
            rf"^(?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"class\s+{re.escape(name)}\b[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*",
            re.MULTILINE,
        )

    # --- Single-line patterns shared across consumers ---
    CLASS_HEADER_ANY_RE: ClassVar[t.RegexPattern] = re.compile(r"^class\s+\w+")
    "Regex: any class header at start of line (no MULTILINE — matches single line)."
    DUNDER_ALL_DECL_RE: ClassVar[t.RegexPattern] = re.compile(r"^__all__\s*:")
    "Regex: ``__all__: ...`` declaration line."
    MODULE_ASSIGNMENT_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^([A-Za-z_]\w*)\s*(?::\s*[^=]+)?=\s*(.+)$"
    )
    "Regex: module-level ``X [: T] = value`` assignment (captures name, value)."

    CHECK_DIRS_REPOSITORY: ClassVar[t.StrSequence] = (
        "src",
        "examples",
        "scripts",
        "tests",
    )
    "All first-class Python roots passed to repository analyzers."

    GITHUB_REPO_URL: ClassVar[str] = "https://github.com/flext-sh/flext"
    "Official GitHub repository URL for the FLEXT project."
    GITHUB_REPO_NAME: ClassVar[str] = "flext-sh/flext"
    "GitHub repository name in owner/repo format."

    # --- Class placement detection (was: class ClassPlacement) ---
    PLACEMENT_PYDANTIC_BASE_NAMES: ClassVar[frozenset[str]] = frozenset({
        "BaseModel",
        "FrozenModel",
        "ArbitraryTypesModel",
        "ContractModel",
        "FrozenValueModel",
        "TimestampedModel",
    })
    "Pydantic model base class names for placement detection."
    PLACEMENT_PROTOCOL_BASE_NAMES: ClassVar[frozenset[str]] = frozenset({"Protocol"})
    "Protocol base class names for placement detection."
    PLACEMENT_ENUM_BASE_NAMES: ClassVar[frozenset[str]] = frozenset({
        "StrEnum",
        "IntEnum",
        "Enum",
    })
    "Enum base class names for placement detection."
    PLACEMENT_UTILITY_NAME_SUFFIXES: ClassVar[frozenset[str]] = frozenset({
        "Utilities",
        "Utility",
    })
    "Class-name suffixes that identify a utility class for placement detection."
    PLACEMENT_CANONICAL_MODEL_FILES: ClassVar[frozenset[str]] = frozenset({"models.py"})
    "Canonical file names where Pydantic models should live."
    PLACEMENT_CANONICAL_PROTOCOL_FILES: ClassVar[frozenset[str]] = frozenset({
        "protocols.py"
    })
    "Canonical file names where Protocol classes should live."
    PLACEMENT_CANONICAL_CONSTANTS_FILES: ClassVar[frozenset[str]] = frozenset({
        "constants.py"
    })
    "Canonical file names where Enum constants should live."
    PLACEMENT_CANONICAL_UTILITY_FILES: ClassVar[frozenset[str]] = frozenset({
        "utilities.py"
    })
    "Canonical file names where utility classes should live."
    PLACEMENT_CANONICAL_MODEL_DIRS: ClassVar[frozenset[str]] = frozenset({
        "_models",
        "models",
    })
    "Canonical directory names where Pydantic models should live."
    PLACEMENT_CANONICAL_PROTOCOL_DIRS: ClassVar[frozenset[str]] = frozenset({
        "_protocols"
    })
    "Canonical directory names where Protocol classes should live."
    PLACEMENT_CANONICAL_CONSTANTS_DIRS: ClassVar[frozenset[str]] = frozenset({
        "_constants"
    })
    "Canonical directory names where Enum constants should live."
    PLACEMENT_CANONICAL_UTILITY_DIRS: ClassVar[frozenset[str]] = frozenset({
        "_utilities"
    })
    "Canonical directory names where utility classes should live."
    PLACEMENT_CANONICAL_TYPING_FILES: ClassVar[frozenset[str]] = frozenset({
        "typings.py"
    })
    "Canonical file names where type aliases should live."
    PLACEMENT_CANONICAL_TYPING_DIRS: ClassVar[frozenset[str]] = frozenset({"_typings"})
    "Canonical directory names where type aliases should live."

    # --- Shared threshold constants (was: class Thresholds) ---
    MIN_UNION_MEMBERS: ClassVar[int] = 2
    "Minimum members for a union type to be normalizable."

    # --- Lint output parsing patterns ---
    LINE_COL_RE: ClassVar[t.RegexPattern] = re.compile(r":\d+(?::\d+)?")
    "Regex: line:col or line:col:col reference in lint output."
    CODE_FRAME_RE: ClassVar[t.RegexPattern] = re.compile(r"^\s*\d+\s*[|+-]")
    "Regex: code/suggestion frame lines ('5 | code', '5 + added', '5 - removed')."
    CODE_FRAME_BODY_RE: ClassVar[t.RegexPattern] = re.compile(r"^\s*\|")
    "Regex: code frame continuation lines."
    UNUSED_IMPORT_RE: ClassVar[t.RegexPattern] = re.compile(
        r"`([^`]+)` imported but unused"
    )
    "Regex: ruff F401 unused import message, capturing the import name."
    LINT_SUMMARY_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(Found \d+ errors?\.|\[\*\] \d+ fixable .*)$"
    )
    "Regex: ruff summary line (Found N errors / N fixable)."

    # --- Semantic versioning (was: class Versioning) ---
    SEMVER_PROJECT_SECTION: ClassVar[str] = "[project]"
    "TOML section header for project metadata."
    # --- Reporting paths (was: class Reporting) ---
    REPORTS_DIR_NAME: ClassVar[str] = ".reports"
    "Standard directory name for report output."


__all__: list[str] = ["FlextInfraConstantsSourceCode"]
